version: "2"

linters:
  default: standard # TODO change to fast and then to all

formatters:
  enable:
    - gci
    - gofmt
    - goimports
    - golines
    - gofumpt
  settings:
    golines:
      max-len: 100
      tab-len: 4
      shorten-comments: true
      reformat-tags: true
      chain-split-dots: true
    gofmt:
      simplify: true
